/* Compile-only coverage of every intrinsic wrapper and immediate interface. */
#include <emmintrin.h>
void simd_header_interfaces(void *p, __m64 m, __m128 a, __m128d d, __m128i i) {
    (void)_mm_cvtsi64_m64(0);
    (void)_mm_cvtm64_si64(m);
    (void)_mm_cvtsi32_si64(0);
    (void)_mm_cvtsi64_si32(m);
    (void)_mm_setzero_si64();
    (void)_mm_set_pi32(0,0);
    (void)_mm_setr_pi32(0,0);
    (void)_mm_set1_pi32(0);
    (void)_mm_set_pi16(0,0,0,0);
    (void)_mm_setr_pi16(0,0,0,0);
    (void)_mm_set1_pi16(0);
    (void)_mm_set_pi8(0,0,0,0,0,0,0,0);
    (void)_mm_setr_pi8(0,0,0,0,0,0,0,0);
    (void)_mm_set1_pi8(0);
    (void)_mm_add_pi8(m,m);
    (void)_mm_add_pi16(m,m);
    (void)_mm_add_pi32(m,m);
    (void)_mm_add_si64(m,m);
    (void)_mm_sub_pi8(m,m);
    (void)_mm_sub_pi16(m,m);
    (void)_mm_sub_pi32(m,m);
    (void)_mm_sub_si64(m,m);
    (void)_mm_adds_pi8(m,m);
    (void)_mm_adds_pi16(m,m);
    (void)_mm_adds_pu8(m,m);
    (void)_mm_adds_pu16(m,m);
    (void)_mm_subs_pi8(m,m);
    (void)_mm_subs_pi16(m,m);
    (void)_mm_subs_pu8(m,m);
    (void)_mm_subs_pu16(m,m);
    (void)_mm_and_si64(m,m);
    (void)_mm_andnot_si64(m,m);
    (void)_mm_or_si64(m,m);
    (void)_mm_xor_si64(m,m);
    (void)_mm_cmpeq_pi8(m,m);
    (void)_mm_cmpeq_pi16(m,m);
    (void)_mm_cmpeq_pi32(m,m);
    (void)_mm_cmpgt_pi8(m,m);
    (void)_mm_cmpgt_pi16(m,m);
    (void)_mm_cmpgt_pi32(m,m);
    (void)_mm_mulhi_pi16(m,m);
    (void)_mm_mullo_pi16(m,m);
    (void)_mm_madd_pi16(m,m);
    (void)_mm_mul_su32(m,m);
    (void)_mm_packs_pi16(m,m);
    (void)_mm_packs_pi32(m,m);
    (void)_mm_packs_pu16(m,m);
    (void)_mm_unpacklo_pi8(m,m);
    (void)_mm_unpacklo_pi16(m,m);
    (void)_mm_unpacklo_pi32(m,m);
    (void)_mm_unpackhi_pi8(m,m);
    (void)_mm_unpackhi_pi16(m,m);
    (void)_mm_unpackhi_pi32(m,m);
    (void)_mm_avg_pu8(m,m);
    (void)_mm_avg_pu16(m,m);
    (void)_mm_max_pi16(m,m);
    (void)_mm_max_pu8(m,m);
    (void)_mm_min_pi16(m,m);
    (void)_mm_min_pu8(m,m);
    (void)_mm_mulhi_pu16(m,m);
    (void)_mm_sad_pu8(m,m);
    (void)_mm_sll_pi16(m,m);
    (void)_mm_sll_pi32(m,m);
    (void)_mm_sll_si64(m,m);
    (void)_mm_srl_pi16(m,m);
    (void)_mm_srl_pi32(m,m);
    (void)_mm_srl_si64(m,m);
    (void)_mm_sra_pi16(m,m);
    (void)_mm_sra_pi32(m,m);
    (void)_mm_slli_pi16(m,0);
    (void)_mm_slli_pi32(m,0);
    (void)_mm_slli_si64(m,0);
    (void)_mm_srli_pi16(m,0);
    (void)_mm_srli_pi32(m,0);
    (void)_mm_srli_si64(m,0);
    (void)_mm_srai_pi16(m,0);
    (void)_mm_srai_pi32(m,0);
    (void)_mm_empty();
    (void)_mm_movemask_pi8(m);
    (void)_mm_stream_pi((__m64 *)p,m);
    (void)_mm_maskmove_si64(m,m,(char *)p);
    (void)_mm_set_ps(0,0,0,0);
    (void)_mm_setr_ps(0,0,0,0);
    (void)_mm_set1_ps(0);
    (void)_mm_set_ps1(0);
    (void)_mm_setzero_ps();
    (void)_mm_set_ss(0);
    (void)_mm_cvtss_f32(a);
    (void)_mm_move_ss(a,a);
    (void)_mm_add_ps(a,a);
    (void)_mm_sub_ps(a,a);
    (void)_mm_mul_ps(a,a);
    (void)_mm_div_ps(a,a);
    (void)_mm_min_ps(a,a);
    (void)_mm_max_ps(a,a);
    (void)_mm_sqrt_ps(a);
    (void)_mm_cmpeq_ps(a,a);
    (void)_mm_cmplt_ps(a,a);
    (void)_mm_cmple_ps(a,a);
    (void)_mm_cmpunord_ps(a,a);
    (void)_mm_cmpneq_ps(a,a);
    (void)_mm_cmpnlt_ps(a,a);
    (void)_mm_cmpnle_ps(a,a);
    (void)_mm_cmpord_ps(a,a);
    (void)_mm_cmpgt_ps(a,a);
    (void)_mm_cmpge_ps(a,a);
    (void)_mm_cmpngt_ps(a,a);
    (void)_mm_cmpnge_ps(a,a);
    (void)_mm_add_ss(a,a);
    (void)_mm_sub_ss(a,a);
    (void)_mm_mul_ss(a,a);
    (void)_mm_div_ss(a,a);
    (void)_mm_min_ss(a,a);
    (void)_mm_max_ss(a,a);
    (void)_mm_sqrt_ss(a);
    (void)_mm_cmpeq_ss(a,a);
    (void)_mm_cmplt_ss(a,a);
    (void)_mm_cmple_ss(a,a);
    (void)_mm_cmpunord_ss(a,a);
    (void)_mm_cmpneq_ss(a,a);
    (void)_mm_cmpnlt_ss(a,a);
    (void)_mm_cmpnle_ss(a,a);
    (void)_mm_cmpord_ss(a,a);
    (void)_mm_cmpgt_ss(a,a);
    (void)_mm_cmpge_ss(a,a);
    (void)_mm_cmpngt_ss(a,a);
    (void)_mm_cmpnge_ss(a,a);
    (void)_mm_and_ps(a,a);
    (void)_mm_andnot_ps(a,a);
    (void)_mm_or_ps(a,a);
    (void)_mm_xor_ps(a,a);
    (void)_mm_unpacklo_ps(a,a);
    (void)_mm_unpackhi_ps(a,a);
    (void)_mm_movemask_ps(a);
    (void)_mm_rcp_ps(a);
    (void)_mm_rsqrt_ps(a);
    (void)_mm_rcp_ss(a);
    (void)_mm_rsqrt_ss(a);
    (void)_mm_movehl_ps(a,a);
    (void)_mm_movelh_ps(a,a);
    (void)_mm_load_ps((const float *)p);
    (void)_mm_loadu_ps((const float *)p);
    (void)_mm_store_ps((float *)p,a);
    (void)_mm_storeu_ps((float *)p,a);
    (void)_mm_stream_ps((float *)p,a);
    (void)_mm_load_ss((const float *)p);
    (void)_mm_store_ss((float *)p,a);
    (void)_mm_cvtsi32_ss(a,0);
    (void)_mm_cvtss_si32(a);
    (void)_mm_cvttss_si32(a);
#ifdef __x86_64__
    (void)_mm_cvtsi64_ss(a,0);
#endif
#ifdef __x86_64__
    (void)_mm_cvtss_si64(a);
#endif
#ifdef __x86_64__
    (void)_mm_cvttss_si64(a);
#endif
    (void)_mm_getcsr();
    (void)_mm_setcsr(0);
    (void)_mm_sfence();
    (void)_mm_load1_ps((const float *)p);
    (void)_mm_loadr_ps((const float *)p);
    (void)_mm_store1_ps((float *)p,a);
    (void)_mm_storer_ps((float *)p,a);
    (void)_mm_comieq_ss(a,a);
    (void)_mm_comilt_ss(a,a);
    (void)_mm_comile_ss(a,a);
    (void)_mm_comigt_ss(a,a);
    (void)_mm_comige_ss(a,a);
    (void)_mm_comineq_ss(a,a);
    (void)_mm_ucomieq_ss(a,a);
    (void)_mm_ucomilt_ss(a,a);
    (void)_mm_ucomile_ss(a,a);
    (void)_mm_ucomigt_ss(a,a);
    (void)_mm_ucomige_ss(a,a);
    (void)_mm_ucomineq_ss(a,a);
    (void)_mm_loadl_pi(a,(const __m64 *)p);
    (void)_mm_storel_pi((__m64 *)p,a);
    (void)_mm_loadh_pi(a,(const __m64 *)p);
    (void)_mm_storeh_pi((__m64 *)p,a);
    (void)_mm_undefined_ps();
    (void)_mm_cvtpi32_ps(a,m);
    (void)_mm_cvtps_pi32(a);
    (void)_mm_cvttps_pi32(a);
    (void)_mm_cvtpi32x2_ps(m,m);
    (void)_mm_cvtpi8_ps(m);
    (void)_mm_cvtpu8_ps(m);
    (void)_mm_cvtpi16_ps(m);
    (void)_mm_cvtpu16_ps(m);
    (void)_mm_cvtps_pi16(a);
    (void)_mm_cvtps_pi8(a);
    (void)_mm_set_pd(0,0);
    (void)_mm_setr_pd(0,0);
    (void)_mm_set1_pd(0);
    (void)_mm_setzero_pd();
    (void)_mm_set_sd(0);
    (void)_mm_cvtsd_f64(d);
    (void)_mm_set_epi64x(0,0);
    (void)_mm_set1_epi64x(0);
    (void)_mm_setzero_si128();
    (void)_mm_cvtsi32_si128(0);
    (void)_mm_cvtsi64_si128(0);
    (void)_mm_cvtsi128_si32(i);
    (void)_mm_cvtsi128_si64(i);
    (void)_mm_set_epi32(0,0,0,0);
    (void)_mm_setr_epi32(0,0,0,0);
    (void)_mm_set1_epi32(0);
    (void)_mm_set_epi16(0,0,0,0,0,0,0,0);
    (void)_mm_setr_epi16(0,0,0,0,0,0,0,0);
    (void)_mm_set1_epi16(0);
    (void)_mm_set_epi8(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
    (void)_mm_setr_epi8(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
    (void)_mm_set1_epi8(0);
    (void)_mm_castps_pd(a);
    (void)_mm_castps_si128(a);
    (void)_mm_castpd_ps(d);
    (void)_mm_castpd_si128(d);
    (void)_mm_castsi128_ps(i);
    (void)_mm_castsi128_pd(i);
    (void)_mm_move_sd(d,d);
    (void)_mm_add_pd(d,d);
    (void)_mm_sub_pd(d,d);
    (void)_mm_mul_pd(d,d);
    (void)_mm_div_pd(d,d);
    (void)_mm_min_pd(d,d);
    (void)_mm_max_pd(d,d);
    (void)_mm_sqrt_pd(d);
    (void)_mm_cmpeq_pd(d,d);
    (void)_mm_cmplt_pd(d,d);
    (void)_mm_cmple_pd(d,d);
    (void)_mm_cmpunord_pd(d,d);
    (void)_mm_cmpneq_pd(d,d);
    (void)_mm_cmpnlt_pd(d,d);
    (void)_mm_cmpnle_pd(d,d);
    (void)_mm_cmpord_pd(d,d);
    (void)_mm_cmpgt_pd(d,d);
    (void)_mm_cmpge_pd(d,d);
    (void)_mm_cmpngt_pd(d,d);
    (void)_mm_cmpnge_pd(d,d);
    (void)_mm_add_sd(d,d);
    (void)_mm_sub_sd(d,d);
    (void)_mm_mul_sd(d,d);
    (void)_mm_div_sd(d,d);
    (void)_mm_min_sd(d,d);
    (void)_mm_max_sd(d,d);
    (void)_mm_sqrt_sd(d,d);
    (void)_mm_cmpeq_sd(d,d);
    (void)_mm_cmplt_sd(d,d);
    (void)_mm_cmple_sd(d,d);
    (void)_mm_cmpunord_sd(d,d);
    (void)_mm_cmpneq_sd(d,d);
    (void)_mm_cmpnlt_sd(d,d);
    (void)_mm_cmpnle_sd(d,d);
    (void)_mm_cmpord_sd(d,d);
    (void)_mm_cmpgt_sd(d,d);
    (void)_mm_cmpge_sd(d,d);
    (void)_mm_cmpngt_sd(d,d);
    (void)_mm_cmpnge_sd(d,d);
    (void)_mm_and_pd(d,d);
    (void)_mm_andnot_pd(d,d);
    (void)_mm_or_pd(d,d);
    (void)_mm_xor_pd(d,d);
    (void)_mm_unpacklo_pd(d,d);
    (void)_mm_unpackhi_pd(d,d);
    (void)_mm_movemask_pd(d);
    (void)_mm_load_pd((const double *)p);
    (void)_mm_loadu_pd((const double *)p);
    (void)_mm_store_pd((double *)p,d);
    (void)_mm_storeu_pd((double *)p,d);
    (void)_mm_stream_pd((double *)p,d);
    (void)_mm_load_sd((const double *)p);
    (void)_mm_store_sd((double *)p,d);
    (void)_mm_load_si128((const __m128i *)p);
    (void)_mm_loadu_si128((const __m128i *)p);
    (void)_mm_loadl_epi64((const __m128i *)p);
    (void)_mm_store_si128((__m128i *)p,i);
    (void)_mm_storeu_si128((__m128i *)p,i);
    (void)_mm_storel_epi64((__m128i *)p,i);
    (void)_mm_stream_si128((__m128i *)p,i);
    (void)_mm_add_epi8(i,i);
    (void)_mm_add_epi16(i,i);
    (void)_mm_add_epi32(i,i);
    (void)_mm_add_epi64(i,i);
    (void)_mm_adds_epi8(i,i);
    (void)_mm_adds_epi16(i,i);
    (void)_mm_adds_epu8(i,i);
    (void)_mm_adds_epu16(i,i);
    (void)_mm_sub_epi8(i,i);
    (void)_mm_sub_epi16(i,i);
    (void)_mm_sub_epi32(i,i);
    (void)_mm_sub_epi64(i,i);
    (void)_mm_subs_epi8(i,i);
    (void)_mm_subs_epi16(i,i);
    (void)_mm_subs_epu8(i,i);
    (void)_mm_subs_epu16(i,i);
    (void)_mm_and_si128(i,i);
    (void)_mm_andnot_si128(i,i);
    (void)_mm_or_si128(i,i);
    (void)_mm_xor_si128(i,i);
    (void)_mm_avg_epu8(i,i);
    (void)_mm_avg_epu16(i,i);
    (void)_mm_min_epi16(i,i);
    (void)_mm_max_epi16(i,i);
    (void)_mm_min_epu8(i,i);
    (void)_mm_max_epu8(i,i);
    (void)_mm_mulhi_epi16(i,i);
    (void)_mm_mulhi_epu16(i,i);
    (void)_mm_mullo_epi16(i,i);
    (void)_mm_mul_epu32(i,i);
    (void)_mm_madd_epi16(i,i);
    (void)_mm_sad_epu8(i,i);
    (void)_mm_packs_epi16(i,i);
    (void)_mm_packs_epi32(i,i);
    (void)_mm_packus_epi16(i,i);
    (void)_mm_cmpeq_epi8(i,i);
    (void)_mm_cmpeq_epi16(i,i);
    (void)_mm_cmpeq_epi32(i,i);
    (void)_mm_cmpgt_epi8(i,i);
    (void)_mm_cmpgt_epi16(i,i);
    (void)_mm_cmpgt_epi32(i,i);
    (void)_mm_unpacklo_epi8(i,i);
    (void)_mm_unpacklo_epi16(i,i);
    (void)_mm_unpacklo_epi32(i,i);
    (void)_mm_unpacklo_epi64(i,i);
    (void)_mm_unpackhi_epi8(i,i);
    (void)_mm_unpackhi_epi16(i,i);
    (void)_mm_unpackhi_epi32(i,i);
    (void)_mm_unpackhi_epi64(i,i);
    (void)_mm_sll_epi16(i,i);
    (void)_mm_sll_epi32(i,i);
    (void)_mm_sll_epi64(i,i);
    (void)_mm_srl_epi16(i,i);
    (void)_mm_srl_epi32(i,i);
    (void)_mm_srl_epi64(i,i);
    (void)_mm_sra_epi16(i,i);
    (void)_mm_sra_epi32(i,i);
    (void)_mm_cmplt_epi8(i,i);
    (void)_mm_cmplt_epi16(i,i);
    (void)_mm_cmplt_epi32(i,i);
    (void)_mm_slli_epi16(i,0);
    (void)_mm_slli_epi32(i,0);
    (void)_mm_slli_epi64(i,0);
    (void)_mm_srli_epi16(i,0);
    (void)_mm_srli_epi32(i,0);
    (void)_mm_srli_epi64(i,0);
    (void)_mm_srai_epi16(i,0);
    (void)_mm_srai_epi32(i,0);
    (void)_mm_movemask_epi8(i);
    (void)_mm_cvtps_pd(a);
    (void)_mm_cvtpd_ps(d);
    (void)_mm_cvtepi32_ps(i);
    (void)_mm_cvtps_epi32(a);
    (void)_mm_cvttps_epi32(a);
    (void)_mm_cvtepi32_pd(i);
    (void)_mm_cvtpd_epi32(d);
    (void)_mm_cvttpd_epi32(d);
    (void)_mm_cvtss_sd(d,a);
    (void)_mm_cvtsd_ss(a,d);
    (void)_mm_cvtsi32_sd(d,0);
    (void)_mm_cvtsd_si32(d);
    (void)_mm_cvttsd_si32(d);
#ifdef __x86_64__
    (void)_mm_cvtsi64_sd(d,0);
#endif
#ifdef __x86_64__
    (void)_mm_cvtsd_si64(d);
#endif
#ifdef __x86_64__
    (void)_mm_cvttsd_si64(d);
#endif
    (void)_mm_lfence();
    (void)_mm_mfence();
    (void)_mm_maskmoveu_si128(i,i,(char *)p);
    (void)_mm_load1_pd((const double *)p);
    (void)_mm_store1_pd((double *)p,d);
    (void)_mm_comieq_sd(d,d);
    (void)_mm_comilt_sd(d,d);
    (void)_mm_comile_sd(d,d);
    (void)_mm_comigt_sd(d,d);
    (void)_mm_comige_sd(d,d);
    (void)_mm_comineq_sd(d,d);
    (void)_mm_ucomieq_sd(d,d);
    (void)_mm_ucomilt_sd(d,d);
    (void)_mm_ucomile_sd(d,d);
    (void)_mm_ucomigt_sd(d,d);
    (void)_mm_ucomige_sd(d,d);
    (void)_mm_ucomineq_sd(d,d);
    (void)_mm_clflush((const void *)p);
    (void)_mm_pause();
    (void)_mm_stream_si32((int *)p,0);
#ifdef __x86_64__
    (void)_mm_stream_si64((long long *)p,0);
#endif
    (void)_mm_loadl_pd(d,(const double *)p);
    (void)_mm_storel_pd((double *)p,d);
    (void)_mm_loadh_pd(d,(const double *)p);
    (void)_mm_storeh_pd((double *)p,d);
    (void)_mm_loadr_pd((const double *)p);
    (void)_mm_storer_pd((double *)p,d);
    (void)_mm_move_epi64(i);
    (void)_mm_loadu_si16((const void *)p);
    (void)_mm_storeu_si16((void *)p,i);
    (void)_mm_loadu_si32((const void *)p);
    (void)_mm_storeu_si32((void *)p,i);
    (void)_mm_loadu_si64((const void *)p);
    (void)_mm_storeu_si64((void *)p,i);
    (void)_mm_undefined_pd();
    (void)_mm_undefined_si128();
    (void)_mm_cvtpi32_pd(m);
    (void)_mm_cvtpd_pi32(d);
    (void)_mm_cvttpd_pi32(d);
    (void)_mm_set_epi64(m,m);
    (void)_mm_setr_epi64(m,m);
    (void)_mm_set1_epi64(m);
    (void)_mm_movpi64_epi64(m);
    (void)_mm_movepi64_pi64(i);
    (void)_mm_malloc(0,0);
    (void)_mm_free((void *)p);
    (void)_mm_extract_pi16(m,0); (void)_mm_insert_pi16(m,0,3); (void)_mm_shuffle_pi16(m,0);
    (void)_mm_extract_epi16(i,0); (void)_mm_insert_epi16(i,0,7);
    (void)_mm_shuffle_ps(a,a,0); (void)_mm_shuffle_pd(d,d,0);
    (void)_mm_shuffle_epi32(i,0); (void)_mm_shufflelo_epi16(i,0); (void)_mm_shufflehi_epi16(i,0);
    (void)_mm_cmp_ps(a,a,0); (void)_mm_cmp_ss(a,a,7); (void)_mm_cmp_pd(d,d,0); (void)_mm_cmp_sd(d,d,7);
    (void)_mm_slli_si128(i,0); (void)_mm_srli_si128(i,255); _mm_prefetch(p,0);
    _MM_TRANSPOSE4_PS(a,a,a,a);
}
